# Generated by Django 5.2 on 2025-04-05 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentorados", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentorados",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="fotos/"),
        ),
        migrations.CreateModel(
            name="DisponibilidadeDeHorarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicial", models.DateTimeField(blank=True, null=True)),
                ("agendado", models.BooleanField(default=False)),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
